name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    name: Publish ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        arch: [x64, arm64]
        exclude:
          - os: windows-2022
            arch: arm64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci

      - run: npm run build
      - run: npm run publish -- --arch ${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
